apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/grafana/alloy.git
    path: operations/helm/charts/alloy/charts/crds/crds
    targetRevision: helm-chart/0.5.1
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
