apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.2.0
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
            - grafana.cluster.tridz.in
          additionalDataSources:
          - name: Loki
            access: proxy
            editable: false
            orgId: 1
            type: loki
            url: http://loki:3100
            version: 1
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: 
       prune: true
       selfHeal: true
